version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:latest
    environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
    volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql

  redmine:
    image: sameersbn/redmine:latest
    depends_on:
    - postgresql
    environment:
    - TZ=Europe/Kiev

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=fm.local
    - SMTP_HOST=ex.fm.local
    - SMTP_PORT=587
    - SMTP_USER=Redmine@fm.local
    - SMTP_PASS=pass
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=true
    - IMAP_HOST=mail.fundament.ua
    - IMAP_PORT=993
    - IMAP_USER=1cithelper@gmail.com
    - IMAP_PASS=pass
    - IMAP_SSL=true
    - IMAP_INTERVAL=

    - INCOMING_EMAIL_NO_ACCOUNT_NOTICE=true
    - INCOMING_EMAIL_DEFAULT_GROUP=Анонимные пользователи
    - INCOMING_EMAIL_PROJECT=battle1csap
    - INCOMING_EMAIL_STATUS=Новая
    - INCOMING_EMAIL_TRACKER=Поддержка
    - INCOMING_EMAIL_PRIORITY=Нормальный
    - INCOMING_EMAIL_PRIVATE=true

    ports:
    - "10083:80"
    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
    # Чтобы далеко не ходить за логами.
    - /srv/docker/redmine/logs:/var/log/redmine
