version: '2'

services: 
 postgresql:
    image: sameersbn/postgresql:latest
    environment:
    - DB_USER=gitea
    - DB_PASS=password
    - DB_NAME=gitea_production
    volumes:
    - /srv/docker/gitea/postgresql:/var/lib/postgresql

 gogs:
  image: gitea/gitea:latest
  restart: 'always'
  links:
  - postgresql

  ports:
    - "10022:22"
    - "10080:3000"

  volumes:
    - /srv/docker/gitea:/data
 